spring:
  datasource:
    url: jdbc:mysql://localhost/cache?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        login-username: sjh
        login-password: 123456
        url-pattern: /druid/*
        enabled: true
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        url-pattern: /*
        enabled: true
  mvc:
    date-format: yyyy/MM/dd
  redis:
    host: 192.168.23.136
    port: 6379